### PR TITLE
feat: support rspack 0.5.7

### PR DESCRIPTION
**Pull request by Magikarp-2020**
https://github.com/Clarkkkk/workbox-rspack-plugin/issues/2

### CODE REVIEW

**Comment by Clarkkkk** [comment]
> find not has`stageOptimizeHash` method.
> 
> https://github.com/Clarkkkk/workbox-rspack-plugin/blob/main/src/inject-manifest.ts#L101
> 
> change code to:
> 
> ```
> compilation.hooks.processAssets.tapPromise(
> ```
> 
> everything runs fine


In fact, the stage is necessary. We need to use the proper stage to get all the assets. If you run `npm run test`, you will find that two tests have failed.

As said in https://github.com/Clarkkkk/workbox-rspack-plugin/issues/2, rspack 0.5.7 and above align its behavior with webpack. So we can fix it by passing the `stage` in `tapPromise`. You can refer to Google's implemention [here](https://github.com/GoogleChrome/workbox/blob/ee62b5b5b9ed321af457a2d962b2a34196a80263/packages/workbox-webpack-plugin/src/generate-sw.ts#L128).

In addition, I think we still need to support rspack 0.5.6, otherwise it would be a breaking change. So we can check if `stageOptimizeHash` exists first, and then use the proper way to tap into the stage.

**Comment by Clarkkkk** [comment]
hi, do you have time to finish this pr? if not, i will fix it.

**Comment by Magikarp-2020** [comment]
> hi, do you have time to finish this pr? if not, i will fix it.

I'm sorry that I didn't see the message. The above problems have been dealt with. If there are still problems, you can close the PR directly and fix it for you.

**Comment by Clarkkkk** [comment]
Thank you!

**Pull request merged**
